# Generated by Django 6.0.3 on 2026-03-25 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('slots_sent', 'Slots Sent'), ('confirmed', 'Confirmed'), ('rescheduling', 'Rescheduling'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('slots_sent_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('follow_up_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scheduling_request', to='candidates.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interviewer_email', models.EmailField(max_length=254)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('tentative', 'Tentative'), ('confirmed', 'Confirmed'), ('released', 'Released'), ('cancelled', 'Cancelled')], default='tentative', max_length=20)),
                ('google_event_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_slots', to='candidates.candidate')),
            ],
            options={
                'ordering': ['start_time'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'confirmed')), fields=('interviewer_email', 'start_time'), name='no_overlapping_confirmed_slots')],
            },
        ),
    ]
