# Generated by Django 6.0.3 on 2026-03-27 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulingrequest',
            name='interviewer_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
