# Generated by Django 6.0.3 on 2026-03-27 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_schedulingrequest_interviewer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewslot',
            name='meet_link',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
