# Generated by Django 6.0.3 on 2026-03-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_interviewslot_meet_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulingrequest',
            name='candidate_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='schedulingrequest',
            name='preferred_date',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='schedulingrequest',
            name='preferred_time',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='schedulingrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('slots_sent', 'Slots Sent'), ('confirmed', 'Confirmed'), ('reschedule_requested', 'Reschedule Requested'), ('rescheduling', 'Rescheduling'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
    ]
