# Generated by Django 6.0.3 on 2026-03-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Screened', 'Screened'), ('Shortlisted', 'Shortlisted'), ('In Interview', 'In Interview'), ('Offer', 'Offer'), ('Hired', 'Hired'), ('Onboarded', 'Onboarded'), ('Rejected', 'Rejected')], default='Applied', max_length=20),
        ),
    ]
