# Generated by Django 6.0.3 on 2026-03-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_alter_candidate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='is_referred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidate',
            name='referral_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
