# Generated by Django 6.0.3 on 2026-03-25 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('equity', models.CharField(blank=True, max_length=255)),
                ('bonus', models.CharField(blank=True, max_length=255)),
                ('reporting_manager', models.CharField(max_length=255)),
                ('custom_terms', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('sent', 'Sent'), ('signed', 'Signed'), ('declined', 'Declined')], default='draft', max_length=20)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('signature_data', models.TextField(blank=True)),
                ('signer_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offer_letter', to='candidates.candidate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
