# Generated by Django 6.0.3 on 2026-03-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='live_lines',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
