# Generated by Django 6.0.3 on 2026-03-25 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slack_invite_sent', models.BooleanField(default=False)),
                ('slack_invite_sent_at', models.DateTimeField(blank=True, null=True)),
                ('slack_user_id', models.CharField(blank=True, max_length=255)),
                ('slack_joined', models.BooleanField(default=False)),
                ('slack_joined_at', models.DateTimeField(blank=True, null=True)),
                ('welcome_message_sent', models.BooleanField(default=False)),
                ('hr_notified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_record', to='candidates.candidate')),
            ],
        ),
    ]
